version: '3'
services:
  datascience:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: docker-ds:cpu
    env_file:
        - .env
    volumes:
        - "${project}:/root/project"
