FROM ubuntu:16.04

LABEL maintainer="Manraj Singh Grover <manrajsinghgrover@gmail.com>"

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python \
        python-dev \
        rsync \
        software-properties-common \
        unzip \
        wget

WORKDIR "/root"
CMD ["/bin/bash"]