version: '3'
services:
  datascience:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: docker-ds:cpu
    ports:
      - "8991:8888"
    env_file:
        - .env
    volumes:
        - "${root}:/root"
        - "${project}:/root/project"
